name: ci

on:
  pull_request:

jobs:
  lint-bash-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Lint Bash scripts
        uses: docker://koalaman/shellcheck-alpine:v0.7.0
        with:
          args: .github/lint-scripts.sh

  lint-docker-file:
    runs-on: ubuntu-latest
    needs: lint-bash-scripts
    steps:
      - name: Checkout
        uses: actions/checkout@v1    
      - name: lint zammad dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: Dockerfile

  test-docker:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs: 
      - lint-bash-scripts
      - lint-docker-file
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: build docker containers
        run: docker build --pull --no-cache --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" -t zammad .
      - name: docker run
        run: docker run -i --name zammad-test --rm zammad
      - name: add autowizard file
        run: docker cp .github/auto_wizard.json zammad-test:/opt/zammad
      - name: run tests
        run: .github/tests.sh
